### ISSUE TITLE
Preview wizard: if no documents exist for selected custom step collection, preview will fail

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#104]
{"timestamp":"2020-03-18T09:30:30.147+0000","status":500,"error":"Internal Server Error","message":"Local message: failed to apply resource at resources/vppBackendServices: Bad Request. Server Message: XDMP-ARGTYPE: xdmp.documentGetCollections(null) -- arg1 is not of type String","path":"/v1/resources/vppBackendServices"}

**Comment by sashamitrovich** [comment]
Idea: prevent listing custom steps if no documents exist for the defined collection.

**Comment by sashamitrovich** [comment]
@epoilvet , could you check for this on the backend if no docs exist for this collection?

**Comment by danielholgate** [comment]
This is the same symptom as this ticket https://github.com/marklogic-community/pipes/issues/75
It's likely the same thing

**Comment by sashamitrovich** [comment]
I think you are right!
