### ISSUE TITLE
Overriding application.properties does not work

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#105]
Are you sure java -jar marklogic-pipes-1.0-beta.4.jar --spring.config.name=application-docker.properties will work? We need a fix to get this working.

**Comment by sashamitrovich** [comment]
This works:

java -jar marklogic-pipes-1.0.1.jar --spring.config.location=application-docker.properties

Try and let me know.

**Comment by sashamitrovich** [comment]
@josvanroosmalen , please confirm it works so we can close this.

**Comment by josvanroosmalen** [comment]
Yes this works. Closing
