### ISSUE TITLE
Save flows to Staging as flow-developer

### ISSUE THREAD

**Issue by michelderu** [marklogic-community/pipes#106]
As a flow-developer I want to be able to save my flows to the staging database.
Somehow this only works when logged in as admin user.

**Comment by sashamitrovich** [comment]
Which roles(s) does the logged-in user have, @michelderu ?

**Comment by michelderu** [comment]
The DHF roles for user flow-developer. So role is flow-developer-role and all that is inherited underneath under DHF 5.2.

**Comment by sashamitrovich** [comment]
@epoilvet, I remember we were checking this but now sure if we tested in the end. Could you check if a user with flow-developer role can save/load graphs, please?

**Comment by sashamitrovich** [comment]
Bug confirmed. Tried saving a graph with flow-developer and got error:

```{"timestamp":"2020-03-20T09:48:07.866+0000","status":500,"error":"Internal Server Error","message":"Local message: failed to apply resource at resources/vppBackendServices: Internal Server Error. Server Message: XDMP-MUSTHAVEUPDATE: xdmp.documentInsert(\"/marklogic-pipes/savedGraph/My Graph.json\", ObjectNode({\"models\":[], \"executionGraph\":{\"last_node_id\":2, \"last_link_id\":1, ...}, ...}), (), \"marklogic-pipes/type/savedGraph\", 0) -- Document must have at least one update permission. Assigned permissions: () . See the MarkLogic server error log for further detail.","path":"/v1/resources/vppBackendServices"}```

**Comment by epoilvet** [comment]
Fixed in master
