### ISSUE TITLE
deployBackend=true conflicts with mlBundle

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#107]
IF you mix deployBackend=true with a mlBundle, this will result in conflicting updates, because the deployBackend will write the files to the project folder which mlBundle also will try to deploy.

Solutions:

- Retire deployBackend. However this makes first start harder. 
- deployBackend should write to user temp directory and module loader should load from there. 

Jos

**Comment by peetkes** [comment]
It would be great if for instance the MarkLogic quickstart would take the build.gradle into concern as that would deploy the pipes modules when you pull that in with mlBundle

**Comment by sashamitrovich** [comment]
Hmmmmmm...I really like the --deployBackend feature, it's super handy for beginners. Agreed that it makes less sense on projects (vs. demo-ing only). Let me think about some potential other solutions (like doing something to prevent conflicting updates).

**Comment by sashamitrovich** [comment]
How about if --deployBackend would not copy modules to the DHF project (FS) and instead just push modules directly to the DB?

**Comment by taatuut** [comment]
I think it is 'safer' and more common/generic to copy to DHF project FS only, like mlBundle mechanism does.

**Comment by peetkes** [comment]
But then quick-start should honor that as well!

**Comment by sashamitrovich** [comment]
There's no fix for this, we're using gradle to deploy.
Chose one approach and stick with it.

**Comment by sashamitrovich** [comment]
Made the documentation more clear.
