### ISSUE TITLE
Create mlBundle for Runtime Library

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#110]
The existing mlBundle need to be broken down: 

- **Runtime bundle.** Which contains all code needed to run compiled code. For now this is only `coreFunctions.sjs`.
- **Development bundle**. This bundle depends  on (includes) Runtime bundle but also the stuff to run Pipes (such as the REST backend, `core.sjs` etc)

**Comment by sashamitrovich** [comment]
Why does it need to be broken down?
