### ISSUE TITLE
Flashing 401 error at startup

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#120]
When you supply the username via `application.properties` you see 1 time a flash with a 401. This happens only once (first time after the JAR is started and the page is requested).

See screenshot below.

![image](https://user-images.githubusercontent.com/9380618/77580769-dc884500-6edc-11ea-9d6e-36ed664de738.png)

**Comment by danielholgate** [comment]
Fixed and waiting for @josvanroosmalen to confirm

**Comment by josvanroosmalen** [comment]
This is now fixed in master. Closing
