### ISSUE TITLE
Better block clipping and resize possibilities

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#121]
Some blocks are not resizable, and also things get rendered outside their blocks. 

![image](https://user-images.githubusercontent.com/9380618/77620728-4c2d1d00-6f3b-11ea-8eef-033ac35da26b.png)

**Comment by danielholgate** [comment]
BEFORE <img width="465" alt="BEFORE" src="https://user-images.githubusercontent.com/13762269/77762393-bf1cbd80-7039-11ea-9b32-83b7b3c51c1d.png">

AFTER
<img width="374" alt="AFTER" src="https://user-images.githubusercontent.com/13762269/77762412-c8a62580-7039-11ea-8b70-7368684554a2.png">

**Comment by danielholgate** [comment]
Fixed
