### ISSUE TITLE
Feature/Lookup is still not dynamic

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#122]
@danielholgate did great work, but it is still not dynamic. 

The number of sliced fields is still hardcoded (in execution) to the number of fields added hardcoded in `core.sjs`. 

For example we have in the latest commit 10 hardcoded `valuePaths`, however this limits the extraction to 10 in execution.  If you put in the editor `nbOfValuesPath` on 15 then the last 5 do not work in preview.

This should be removed because we build this dynamic. During execution this seems not to be build dynamic, so then we are stuck to 10.  If you remove this entirely from `core.sjs` the block will not work anymore because during execution this is not build dynamically. 

```
    this.value0Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.value1Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.value2Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.value3Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.value4Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.value5Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.value6Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.value7Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.value8Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.value9Path = this.addWidget("text","nbOutputValues", "", function(v){},  { } );
    this.addOutput("val0");
    this.addOutput("val1");
    this.addOutput("val2");
    this.addOutput("val3");
    this.addOutput("val4");
    this.addOutput("val5");
    this.addOutput("val6");
    this.addOutput("val7");
    this.addOutput("val8");
    this.addOutput("val9");
```

**Comment by danielholgate** [comment]
Can you confirm where the code you showed above is? Is it currently in the project

**Comment by josvanroosmalen** [comment]
This code is in `core.sjs`. If you reduce this to 1 (so  `value0path`and `val0`  only, you will see that it is not executing for paths > 1. So the execution parts is limited to the number of hardcoded ones (in this case 10).

**Comment by danielholgate** [comment]
Not possible to make this dynamic, but simply providing 20 outputs solves the problem for every realistic situation
