### ISSUE TITLE
Lookup & LookupCollectionPropertyValue empties the paths

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#130]
Daniel,

We still need another fix for `Lookup` & `LookupCollectionPropertyValue`

If `nrOfValues` is on 3 and we change it to 4, it also clears the paths of valuePaths0-2, so you need to re-enter the paths 0-2.

**Comment by danielholgate** [comment]
Pushed fixed. Awaiting confirmation from @josvanroosmalen

**Comment by josvanroosmalen** [comment]
looking good. closed
