### ISSUE TITLE
Setup Unit Test framework

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#135]
Setup a Unit Test framework, with 2 test-cases (for demo) with 2 graphs. 

The idea here is: 

We have N test-cases. For each test case we:

- Have a graph
- We have an input doc
- We have expected output. 
- The unit test framework should:
   * Run the preview and store the result
   * Run the code generator, and execute the code, and store the result
  * Both results should be compared to expected output, and deviations should be reported. 

This setup should be easy to expand (e.g. add new test cases).

**Comment by sashamitrovich** [comment]
@josvanroosmalen , this unit testing framework is already set up in the Java middle tier and there are some sample unit tests. I can present this in an internal call. The challenge is to produce: input document, graph and output document for the tests we want to cover. 

We should establish a rule that the ticket cannot be closed until this is provided. Let's discuss internally.

**Comment by josvanroosmalen** [comment]
Can we see this this wednesday?
