### ISSUE TITLE
Sort Collections in Source block and Preview on collection name

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#137]
Currently the collections in both source block and preview are in "random" order (probably the way it is returned from the lexicon). This does not make any sense. Sort it ascending on collection name.

**Comment by danielholgate** [comment]
The collections in the drop downs are currently sorted alphabetically. Can you please attach a screen shot

**Comment by josvanroosmalen** [comment]
Yes it is sorted, but uppercase (Z) comes before lowercase (a). That is not really natural.

**Comment by danielholgate** [comment]
fixed awaiting confirmation from @josvanroosmalen
