### ISSUE TITLE
Improve Entity Selection Panel

### ISSUE THREAD

**Issue by danielholgate** [marklogic-community/pipes#160]
- Add descriptions (if any) from entity services model for Entity and Properties and display in UI
- Clean up UI - Font sizing / layout
- Block preview? Or just improvedlist?
- Validation on Entity Creation (no Entity Block without properties)

**Comment by sashamitrovich** [comment]
I assume this can't be tested with a graph. 
So, if you've merged it into master, let's close, @danielholgate ?

**Comment by danielholgate** [comment]
Yep agree. Closing
