### ISSUE TITLE
Hook for property editing

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#162]
Implement a hook for property editing. This is useful for custom blocks to provide a big edit window. 

Implement the hook and provide an example in `Examples/CustomModules/user.{sjs,json}`

**Comment by josvanroosmalen** [comment]
The dialogs for Query/MapValues should preferable be removed from `ml-litegraph.vue` and moved to `core.vue` or `core.sjs` and work via those hooks. So that all block functionality are stored on a single place.

**Comment by danielholgate** [comment]
I've updated the core blocks which had double click pop-ups to now use the new hook. 
For example, the Lookup block in core.json does it (via editProp and editWindowTitle properties), and also does a very simply validation of the content before save via the (optional) beforePropSave event

**Comment by danielholgate** [comment]
Will create an example for external/user blocks

**Comment by josvanroosmalen** [comment]
Can you also refactor the mapping values / cts values away via the new hooks? So remove that from `ml-litegraph.vue` ?

**Comment by danielholgate** [comment]
Cts values is already using the new hook.

Only the Mapping values block is not using it because it has a very specialized editing window. 
If this is ever moved out of ml-litegraph let's do it in a separate ticket

**Comment by josvanroosmalen** [comment]
Thanks daniel. Can you also externalize the mapping property editor (well basically all property editors)? Also, now you you have property validation, the query editor should check something is a valid instance of cts.query. If it is not a cts.query it should give an alert.

**Comment by danielholgate** [comment]
Closing this ticket as it addresses the creation of hooks. 
Implementing specific validation checks using the hooks, and externalising the mapping property editor should be separate tickets (the mapping property editor is very specific to one block though, not sure it really makes sense to externalise that one)
