### ISSUE TITLE
User blocks are not visible if customModulesRoot is not set. 

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#174]
We need to give a WARNING if the customModulesRoot is not set, so that it become clear in the log that the user blocks are not visible.

**Comment by sashamitrovich** [comment]
Why only for customModulesRoot and not for all variables?
Sounds like an issue with someone not reading the README properly rather than a problem in the application, really. I would decline this ticket if you haven't already committed, to be honest.

**Comment by josvanroosmalen** [comment]
Well I do not agree with this. We can also add other properties checking as well but that is a different story. The idea is that the user get quickly ideas what the problem is.  You want that software operates as much as possible without the need of a manual.

**Comment by sashamitrovich** [comment]
OK, what about the users who don't use user blocks and have no intention to use them?
Now, they will be confronted with a warning (not info):

"USER BLOCKS UNAVAILABLE! Property customModulesRoot not set in the application properties."

As a user, I'd think I'm doing something wrong (I'm being shouted at in an uppercase warning).

**Comment by josvanroosmalen** [comment]
Ok we can change that.

**Comment by sashamitrovich** [comment]
Change to INFO, please. it's an informational message, the app can't know what the user wants.
