### ISSUE TITLE
If preview causes an Error we want to know the URI

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#179]
Upon request of Michel de Ru:

- If we select Random preview, the preview might crash (for what kind of reason). We want to get feedback which URI we are processing. Maybe we can show the URI in the red message box as well. 

- Also the Red Error Message box is only show for a very short period and the user is not able to copy the data (such as the URI which we are going to add there ;-) ) .

**Comment by danielholgate** [comment]
Fixed
