### ISSUE TITLE
Allow me to collapse the setup stuff on the Preview

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/pipes#182]
After I setup the preview, I'd like to hide the setup bits from view with a disclosure or some such. As it is, it takes up a lot of valuable real estate and makes viewing the preview a bit difficult.

![image](https://user-images.githubusercontent.com/630382/78784203-ea28da80-7972-11ea-8418-885b7f211a91.png)

**Comment by sashamitrovich** [comment]
Fixed.
