### ISSUE TITLE
User.json is unfriendly - check for its validity on Pipes startup

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#187]
User.json is user unfriendly if it contains relatively "stupid" mistakes. Eg if you add an extra comma between the blocks none of not all blocks are visible without warning. If you add an extra } or { somewhere in a block the JSON is not valid and without warning the block is not shown.

Proposed solution: write a simple litegraph JSON schema and test this in the Java tier upon startup. If it is invalid, refuse to start

**Comment by sashamitrovich** [comment]
Done.

**Comment by sashamitrovich** [comment]
OK, I’ve got the basic checks going

https://github.com/marklogic-community/pipes/blob/release/1.1-candidate/java-middle-tier/src/main/resources/schema/user_schema.json

that’s the schema definition
let me know if you want more stuff there
your basic stuff with extra commas, brackets etc. (json structure) is covered even without the schema but we can extend the schema to add mandatory elements...
