### ISSUE TITLE
Graph JSON pretty print when downloading

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#188]
Pretty print the Graph JSON upon download (e.g. add newlines). 

Now it creates JSON with everything on 1 line, however that is not convenient for version control systems to detect changes.

**Comment by danielholgate** [comment]
Agree this is a good idea. Will address

**Comment by danielholgate** [comment]
Fixed

**Comment by sashamitrovich** [comment]
tested.
