### ISSUE TITLE
Drop-downs should have auto-completion

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#191]

**Comment by danielholgate** [comment]
Created branch features/AutocompleteDropdowns and pushed first attempt at this for Source Block wizard db and collection drop downs.
Everyone can try it out and give feedback

**Comment by sashamitrovich** [comment]
Found one strange behaviour:
when selecting collection, if using mouse-scroll, the field gets detached and "floats"

<img width="682" alt="Screenshot 2020-05-19 at 09 05 01" src="https://user-images.githubusercontent.com/15609655/82295357-f1022e80-99af-11ea-93d5-9857dca47153.png">
