### ISSUE TITLE
Graph execution sometimes fails with xdmp.documentGetCollections(null) -- arg1 is not of type String

### ISSUE THREAD

**Issue by danielholgate** [marklogic-community/pipes#20]
Seems to be random/when execute button in preview clicked very rapidly

```Error is "Info: Status 500: XDMP-ARGTYPE: xdmp.documentGetCollections(null) -- arg1 is not of type String" (even though collection is set in UI)```

also seen in backend MarkLogic logs

**Comment by sashamitrovich** [comment]
Has this been fixed, @danielholgate, @epoilvet?
Any idea under which commit?

**Comment by epoilvet** [comment]
Supposed to be fixed with https://github.com/marklogic-community/pipes/commit/1dae3652dbfc0ff006178b286650b283e3eeacd3
