### ISSUE TITLE
When I save the graph under a different name, the name of the graph in the top bar doesn't refresh

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#203]
<img width="1383" alt="Screenshot 2020-04-17 at 15 49 50" src="https://user-images.githubusercontent.com/15609655/79576177-28d13a00-80c3-11ea-89bd-bc1ba1681c53.png">

**Comment by danielholgate** [comment]
Fixed. Awaiting confirmation testing

**Comment by sashamitrovich** [comment]
Fixed.
