### ISSUE TITLE
RESTAPI-INVALIDREQ:/marklogic.rest.resource/vppBackendServices/assets/resource.xqy not found

### ISSUE THREAD

**Issue by swarupMarklogic** [marklogic-community/pipes#205]
Hi Team,
How to fix this below issue  
com.marklogic.client.FailedRequestException: Local message: failed to read resource at resources/vppBackendServices: Bad Request. Server Message: RESTAPI-INVALIDREQ: (err:FOER0000) Invalid request:  reason: Extension vppBackendServices or a dependency does not exist: XDMP-MODNOTFOUND: (err:XQST0059) Module /marklogic.rest.resource/vppBackendServices/assets/resource.xqy not found

**Comment by danielholgate** [comment]
Sounds like the backend hasn't been deployed. When you run Pipes for the first time you need to deploy the backend libraries the tool uses. You do this by running the jar and including the **--deployBackend=true flag**

**Comment by swarupMarklogic** [comment]
Thanks for the quick response ..it is working !!

**Comment by sashamitrovich** [comment]
Great, keep creating tickets here if you run into problems. Thanks!

**Comment by danielholgate** [comment]
Great to hear! We will have a new release coming very soon with an improved UI and new features/fixes with a focus on usability
