### ISSUE TITLE
Update the documentation and sample graphs

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#207]

**Comment by epoilvet** [comment]
Idea: create sample graphs based on most used open data sources with for each :
- Pipes graph to harmonize
- DHF entities

Exemple : National drug database with medications distributed within countries.
For France dataset is here:
http://base-donnees-publique.medicaments.gouv.fr/telechargement.php

There are  N to N mappings, harmonisation and other rules to be applied.
Same dataset exists for all countries.

**Comment by sashamitrovich** [comment]
Done.
