### ISSUE TITLE
Create a query builder

### ISSUE THREAD

**Issue by epoilvet** [marklogic-community/pipes#208]
Could leverage something like https://dabernathy89.github.io/vue-query-builder/ with suggestions based on a selected collection

**Comment by sashamitrovich** [comment]
1. Have 2 output nodes:
- Result
- ctsQuery
2. Rename "Expert Query Builder" to "Lookup"
3. Remove following blocks: @epoilvet please add which ones
4. To be merged to 1.2 when tested (and ready)
5. Help users migrate their graphs (TopGun @wpaven )

**Comment by sashamitrovich** [comment]
From @epoilvet:

So regarding block deletion thanks to new query builder, I suppose we can remove almost everything from query and I would only keep:
- LookupCollectionPropertyValue renamed to LookupByValue (or something like that)
- new query building ==> LookupByQuery
- Document by Uri (could be usefull)
All the other can be removed I think

**Comment by sashamitrovich** [comment]
Done.
