### ISSUE TITLE
[BUG]: Subgraph fails

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#210]
[TestSubgraph.json.zip](https://github.com/marklogic-community/pipes/files/4515982/TestSubgraph.json.zip)

Add a document:

```
'use strict';
declareUpdate()
let doc={
  "a": 5,
  "b": 6
}

xdmp.documentInsert("/test/input.json",doc, {collections:"test"})
```

**Comment by sashamitrovich** [comment]
@epoilvet , could you have a look (not urgent), it seems another to be another regression as a consequence of the merge of new grouping?

**Comment by epoilvet** [comment]
It was because of the new naming convention "graph\*" is now "Graph\*".
Fixed

**Comment by sashamitrovich** [comment]
Unit test aded.
