### ISSUE TITLE
Creating source block duplicates elements in the source tree for mixed collection

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#22]
This happens when the source collection contains both json and xml. @danielholgate , can you add the source samples and the screenshot, please?

**Comment by sashamitrovich** [comment]
@epoilvet , do you think you can tackle this?

you need 1 XML and 1 JSON doc with the "same" structure in order to test

<root><name>john</name></root>

{"root":{"name":"paul"}}

**Comment by epoilvet** [comment]
Done: the bug is due to son xpath generate by xdmp.path ==> it return /../../text("propertyName"), on XML the result is  /../../propertyName
