### ISSUE TITLE
Reduce the amount of log

### ISSUE THREAD

**Issue by jeremybrunetML** [marklogic-community/pipes#225]
Reduce the amount of log

**Comment by josvanroosmalen** [comment]
I changed the title: reduce the amount of log, because I do not agree with "change log level". 

There are 2 kinds of logs:

- Log added (also by me) temporary to investigate issues. This can be removed. 
- Valuable log. This should be placed behind  `xdmp.trace`, so that it can be turned on/off

**Comment by peetkes** [comment]
Added trace events
- pipes-vpp an pipes-vpp-details => all logs for the vppBackendService
- pipes-graphHelper and pipes-graphHelper-details => all logs for the pipes-graphHelper module
- pipes-coreFuntions => all logs for the coreFunctions module
- pipes-core and pipes-core-details => all logs for the core module

**Comment by sashamitrovich** [comment]
Add documentation.

**Comment by sashamitrovich** [comment]
Documented at: https://github.com/marklogic-community/pipes/wiki/Run-and-debug-Pipes-locally
