### ISSUE TITLE
Allow me to auto open a saved Graph on launch

### ISSUE THREAD

**Issue by paxtonhare** [marklogic-community/pipes#226]
I'd like to have Pipes automatically open a saved graph on launch.

**Comment by sashamitrovich** [comment]
How would a user specify which graph they want to open on launch?

**Comment by sashamitrovich** [comment]
@paxtonhare, does it have to be a graph saved in the DB or it would be acceptable to load a graph from the file system? It might be easier to manage the potential issues...

**Comment by sashamitrovich** [comment]
Added new param
--loadGraph-mygraphname
