### ISSUE TITLE
Get rid of application.properties and use gradle.properties

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#227]

**Comment by danielholgate** [comment]
To consider: What if users want to run pipes with a user other than the one defined in the gradle project?

**Comment by sashamitrovich** [comment]
Agreed.

Here's my proposal for the overhaul of the whole log-in experience:

Summary: **The user always has to log on through the UI.** 
Details:

1) We'll use gradle.properties (and derived props) for Pipes to read values from
2) Just like QS UI, we will not use user/pass from the props - user always has to log in with a combination they have to type in
3) When the log in screen pops-up we let user chose their environment (if more that one present like "local" and "DHS") and ask them to type in user/pass
3a) In case no gradle properties file is present, we ask the user to enter host and port name (which point automatically to a DB) - this is in order to support "standalone" usage of Pipes
4) Once the user has logged in successfully, Pipes checks if backend modules are present and in correct version and, if needed, copies & installs them
5) After this, Pipes shows the "New graph" screen
6) Befrore even hitting the UI, Pipes checks the schema for user modules (this only required access to FS, not auth against DB so no login required at this stage) and doesn't start if file invalid (#187)

With this:
- We lower the bar for new users (eliminate application.properties, modules will be installed automatically)
- We allow log-ins with different usernames
- Pipes can be used stand-alone
- Potentially we eliminate those UI glitches where the user hasn't been authorized and UI is broken

@danielholgate , @epoilvet , @josvanroosmalen , WDYT about this? 
Did I miss something?

The effort on the Java part is low for this (and it further simplifies it), the effort on the UI part is also low (some more complexity on the Login screen).

**Comment by sashamitrovich** [comment]
Implementation plan:

- [x] Get rid of --deployBackend
- [x] Get rid of --undeployBackend
- [x] Ignore mlUsername and mlPassword (i.e. don't use them if present, don't check for presence)
- [x] Change README
- [x] No authenticating on start-up
- [x] Authenticate on /login
- [x] Check version of modules and deploy, if needed
- [ ] Don't copy modules to DHF project (only deploy)
- [x] capture incorrect authentication
- [x] sort out the routes in the UI: Login page should be the 1st page that the UI goes to - always.
- [x] switch to using gradle.properties
- [x] support different gradle environments
- [x] adapt documentation
- [x] add "logging in, please wait..." dialog
- [x] fix unit tests

**Comment by sashamitrovich** [comment]
Done.
