### ISSUE TITLE
Sometimes Pipes doesn't load core.json

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#229]

**Comment by danielholgate** [comment]
Eric made commit to address this: 902546b3a658d8085015a1be6d3844faae7f7744

Testing required

**Comment by sashamitrovich** [comment]
Happened again today :(

**Comment by danielholgate** [comment]
This is related to the authentication in the Java layer. 
When the UI calls the back end after first jar start up Java is returning a 401 - I tried adding a "dummy" call first to safely trap the first call, but it's actually every DB call during the very first startup so something to do with the auth.

**Comment by sashamitrovich** [comment]
Should be fixed on 1.1 now, under #227
