### ISSUE TITLE
Restrict file upload to relevant types

### ISSUE THREAD

**Issue by taatuut** [marklogic-community/pipes#23]
When going to FROM FILE I can select any kind of document. E.g. when I pick a PDF and PNG it looks like they get 'uploaded'. Not sure if there is any negative impact but might make sense to restrict to certain file types?

![image](https://user-images.githubusercontent.com/2260360/73032061-3b2e3580-3e3e-11ea-8c05-c729a582a90a.png)

**Comment by danielholgate** [comment]
Fixed. Only .json and .csv uploads are possible
