### ISSUE TITLE
Connection between source block and subgraph doesn't get saved

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#231]
<img width="1246" alt="Screenshot 2020-05-07 at 16 36 20" src="https://user-images.githubusercontent.com/15609655/81307418-ed51dc00-9080-11ea-9cb0-82410d650c0a.png">

**Comment by danielholgate** [comment]
I believe this is fixed by @epoilvet in this commit 
https://github.com/marklogic-community/pipes/commit/435e2343ebef1eb23de4332525a09ddc6bb6027b

Please re-test (works for me now )

**Comment by sashamitrovich** [comment]
OK, 1st test (just reloading existing graph) worked. 
Will continue testing for more complex scenarios.

**Comment by sashamitrovich** [comment]
OK, I think I found a new bug. Here's how to reproduce:

1. Create New Graph
2. Add a Subgraph

Notice it has no output node. Go into subgraph, it has output node. Go out - no node.
Output node lost.

**Comment by epoilvet** [comment]
Latest version of Litegraph is now pushed to 1.1 with a fix for this issue
