### ISSUE TITLE
rename FlattenArray to stringJoin

### ISSUE THREAD

**Issue by kghmanuel** [marklogic-community/pipes#238]
The "term" flatten when used on array usually denotes having an N-dimensional array reduced to a single dimensional array. The current behavior (and even the output name) actually concatenates the values.

![image](https://user-images.githubusercontent.com/421770/81906974-aa9c8080-95f9-11ea-96a2-23abb3b7d2ab.png)

**Comment by danielholgate** [comment]
Fixed
