### ISSUE TITLE
LookupCollectionPropertyValue datatype does not work

### ISSUE THREAD

**Issue by kghmanuel** [marklogic-community/pipes#239]
![image](https://user-images.githubusercontent.com/421770/81907471-68c00a00-95fa-11ea-8778-fcf6ac3b5a9c.png)

If the xpath corresponds to a string property. The datatype of number does not try to convert the value to an actual number. The above image will still return an actual number if i change the datatype to string.

**Comment by sashamitrovich** [comment]
@danielholgate , could you have a look?

**Comment by sashamitrovich** [comment]
This block has been deprecated and replaced by the new Lookup by Query block.
