### ISSUE TITLE
Use Graph title when saving

### ISSUE THREAD

**Issue by danielholgate** [marklogic-community/pipes#25]
Graphs/Steps have a "Title" (left panel), but when you "Save graph" the dialog asks for a name to save the Graph under. 

<img width="311" alt="Screen Shot 2020-01-27 at 09 50 46" src="https://user-images.githubusercontent.com/13762269/73160948-9e43f480-40ea-11ea-88cd-065289dfe895.png">

Two enhancements around this:

1. Save dialog should use the "title" as default value in the pop up.  Users can then change/modify this at save time and changes in popup also update the Title. 
2.  Using an existing (in DB) graph name should pop up a warning before save to ensure user is aware they'll overwrite

**Comment by sashamitrovich** [comment]
Tested, works, thanks.
