### ISSUE TITLE
[BUG] "Save result to database" is ignoring the defined URI and collection in the envelope

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#258]
**Describe the bug**
Saving the document from the preview in the DB will:
- ignore the URI defined in the envelope
- ignore the collections in the envelope
-very likely, ignores multiple documents (array)

**Comment by danielholgate** [comment]
Does this also occur when the graph is deployed to DHF step and run there? (as it would "in production" ?)

**Comment by sashamitrovich** [comment]
No, just when saving the doc from the Preview wizard.

**Comment by epoilvet** [comment]
Looks like an old regression introduced with the preview URI info generation. 
Fixing it
