### ISSUE TITLE
[FEATURE] Limit the ability of a Pipes user to kill the server

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#260]
One example: the query builder(s)/lookup can return an unlimited number of documents. Theoretically, someone could load the entire database content when running a graph.

How can we handle this?

**Comment by josvanroosmalen** [comment]
We do not handle this. In Query console you can also load a "unlimited" number of documents. The server will not be killed, this will cause runtime timeouts, or Javascript memory errors once start reading the sequence and do something else with it.
