### ISSUE TITLE
[BUG] When closing a subgraph, the title still says: "Subgraph: Subgraph"

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#261]
@danielholgate , this looks like a regression. Could you have a look, please?

**Comment by sashamitrovich** [comment]
@epoilvet , I think this might be a regression after upgrading litegraph. Could you have a look ?

**Comment by danielholgate** [comment]
@sashamitrovich @epoilvet  I'll look at this as I implemented this originally

**Comment by sashamitrovich** [comment]
Works.
