### ISSUE TITLE
[BUG] Caching of user.json is causing issues during development

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#274]
Need to find a way to prevent the browser from caching the user.json.

**Comment by taatuut** [comment]
You might wanna check the tips I sent previously regarding caching, I don't think these are all implemented yet. If user.json is requested via GET, adding a unique (time)stamp or similar to the request uri can help. Other approach could be to use POST in the browser to request the user.json (POST requests should not be cached until explicitly stated by adding appropriate headers. If this is developer only, and you are on Chrome you could also disable caching in the Developer Tools > Network > Disable Cache.

**Comment by sashamitrovich** [comment]
The user.json is requested by litegraph. To change how it is requested (POST vs GET or file name changes...), we'd need to change the litegraph core. That makes it super hard to upgrade litegraph later. That's why this is not very practical.

The solution to the problem is disabling the cache.
And yes, disabling caching in Chrome is one way but it's a workaround that requires an action from the user.

The ideal solution is we make this work for the user without them having to do anything (cleaning/disabling cache, refreshing, running in incognito mode) by the web server telling the browser not to cache.

The problem is really when using Quasar dev to serve the statics. Need to discover the proper switch that does it (ie configure Cache-Control for Quasar).
Found that configuration param for Spring Boot so the problem will not appear anymore when Spring Boot is serving the statics.

**Comment by sashamitrovich** [comment]
The issue has been localized to quasar only.
