### ISSUE TITLE
[FEATURE] Create a FilterArray block

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#280]
<img width="443" alt="Screenshot 2020-07-22 at 10 36 55" src="https://user-images.githubusercontent.com/15609655/88154557-502a2c80-cc07-11ea-934c-90ff9e9071d1.png">

**Comment by peetkes** [comment]
To use this block connect an array of strings you want to filter to 'unfiltered', connect an array of strings you want to filter on to 'patterns'
when 'include' equals true filtered will contain every value from unfiltered that exists in patterns.
when 'include' equals false filtered will include every value from unfiltered that does NOT exist in patterns.
