### ISSUE TITLE
[BUG] hardcoded maximum number of steps visible in step overview?

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/pipes#284]
I have created 7 different steps in my dhf project. 
When I try to save a graph module into the database I only see the first 5 step definition names.

If I investigate some more I can see only 5 steps in the call to http://localhost:9081/customSteps
So I'm guessing there is a hard coded maximum number of steps somewhere.
![image](https://user-images.githubusercontent.com/550788/90370542-d8b4b500-e06d-11ea-8f41-cb29ab8c5324.png)

As response to http://localhost:9081/customSteps:
![image](https://user-images.githubusercontent.com/550788/90370583-eb2eee80-e06d-11ea-89de-611565950dcb.png)

What you see in the pipes UI:
![image](https://user-images.githubusercontent.com/550788/90370707-20d3d780-e06e-11ea-91f3-cf5728e43772.png)

**Comment by sashamitrovich** [comment]
Possible explanation: If a step doesn’t have neither a source collection nor a query, it will not be returned (as it’s useless for Pipes)

On 17. Aug 2020, at 09:42, Peter Kester <notifications@github.com> wrote:

﻿

I have created 7 different stepos in my dhf project. When I try to save a graph module into the database I only see the first 5 step definition names.

If I investigate some more I can see only 5 steps in the call to http://localhost:9081/customSteps
So I'm guessing there is a hard coded maximum number of steps somewhere.
[image]<https://user-images.githubusercontent.com/550788/90370542-d8b4b500-e06d-11ea-8f41-cb29ab8c5324.png>

[image]<https://user-images.githubusercontent.com/550788/90370583-eb2eee80-e06d-11ea-89de-611565950dcb.png>

**Comment by peetkes** [comment]
all steps have a sourcequery

**Comment by peetkes** [comment]
Ah, makes sense
