### ISSUE TITLE
[BUG] We are losing the stack trace

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#287]
Stack trace is not printed during graph execution error.

2020-09-18 22:34:12.570 Error: Exception occured during graph execution: TypeError: (intermediate value)(intermediate value)(intermediate value).xpath is not a funct

Will fix in 1.4

**Comment by sashamitrovich** [comment]
Did you know that we’ve introduced:

https://github.com/marklogic-community/pipes/wiki/Run-and-debug-Pipes-locally#tracing-events-pipes-modules-running-on-marklogic

To control the amount of logs produced?

**Comment by josvanroosmalen** [comment]
Well, there is much more wrong. 

- Add a query block which uses a collection query X
- Add a XPath block to the output
- Connect input to query and xpath to output
- Run this graph on collection X. 
- Now this is causing errors in the backend, but this is become not visible in UI:

**GRAPH:**

![image](https://user-images.githubusercontent.com/9380618/93848922-2c3ca300-fcab-11ea-89bf-8a88db927618.png)

**NO ERROR:**

![image](https://user-images.githubusercontent.com/9380618/93848951-3e1e4600-fcab-11ea-8c11-bcfc9950237d.png)

**ERROR IN THE LOG:**

![image](https://user-images.githubusercontent.com/9380618/93848993-51311600-fcab-11ea-8c3a-b57eae51eedf.png)
