### ISSUE TITLE
Working with Entities: notification for a block when underlying Entity changes

### ISSUE THREAD

**Issue by taatuut** [marklogic-community/pipes#30]
At the moment, Entity blocks are fixed at creation time.

Is there a preferred way to work with Entities getting updated in Pipes? Say you add new property to an Entity, do you have to create another block first, remove existing from graph, and redo connecting new block with input output? Or are there other options? Similar question for removing or editing Entity properties. 

An enhancement would be to notify users when an entity underlying a block changes. This would at least make user aware and give him possibility to act -> manually recreate it.. Auto-recreating/updating the block could be problematic because properties could disappear or be renamed and would break existing connections. But doing nothing for updated entities will break the graph too?

Ideally, Pipes should draw a warning sign on an Entity block if it notices that the Entity definition in DHF has changed. This could be triggered by re-loading the graph. Depending on change automated actions could be executed.

**Comment by danielholgate** [comment]
Added code which checks graphs on reload (from DB or exported file) and detects differences between the Entities defined in the graph vs what is in DB now. Other half of this is how we notify the users, and what they need to do to resolve this situation vs what we can/should do automatically

**Comment by danielholgate** [comment]
Fixed back end. Front end code by Eric in commit 729bc8ef0d2a59d6ed20aaca95d0e3bdf9b85eda
