### ISSUE TITLE
Clean/check parameters in application.properties

### ISSUE THREAD

**Issue by danielholgate** [marklogic-community/pipes#32]
A few problems have been reported recently which were caused by a trailing space which had been accidentally copy/pasted after either the credentials or the DHF path in application.properties. 

Properties should be trimmed so Pipes still works despite these. Possibly also alert the user on the console to the problem so they can correct, but still go ahead and start up with the trimmed values

**Comment by taatuut** [comment]
It hurts others too:
https://htr3n.github.io/2018/11/spring-boot-trailing-whitespaces/
https://stackoverflow.com/questions/58095669/springboot-automatically-trim-trailing-white-space-for-properties-in-props-file
https://riptutorial.com/java/example/12532/property-files-caveat--trailing-whitespace

**Comment by sashamitrovich** [comment]
OK, we can trim trailing and leading spaces for sure and print the message about it. Still, I'm pretty proud that the Java code was at least catching this situation and giving at least some half-baked message that helped solve the issue.

**Comment by sashamitrovich** [comment]
Done.
