### ISSUE TITLE
[BUG] passing through empty triples from source envelope to output envelope fails

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/pipes#326]
Passing through empty triples from source envelope to output envelope fails with an XDMP-ARG message for `xdmp.type(Sequence([]))`.

I created a source block with access to headers, triples, instance, attachments, and was passing triples, instance, and attachments through, because I only needed to append something to the headers. However, triples part was empty (empty array), so an empty sequence was passed through. Core code seems to try to check type of input of the DHF envelope block, and fails on checking if triples is an array or not. We need a better test there..

**Comment by grtjn** [comment]
Wondering if the improvements for 2.0 release fixes this, might be worth a unit test (pass in `Sequence.from([])`, `[]`, and `json:array()`, and see what happens)

**Comment by josvanroosmalen** [comment]
Please add an example graph.

**Comment by grtjn** [comment]
<img width="1667" alt="Screen Shot 2020-10-16 at 9 39 16 PM" src="https://user-images.githubusercontent.com/611397/96301967-40e53000-0ff8-11eb-8fb4-d78577c3ecf2.png">

**Comment by grtjn** [comment]
It is about the line from triples to triples. I can't attach json here, but I can share it offline with you if necessary. It is really simple to recreate though. Pick an entity from final to build the source block, link the four fields 1:1 to the output envelope, and run with an existing entity from final. You'll see some odd results or errors with v1 pipes..

**Comment by grtjn** [comment]
Note: preview with an entity that has no triples.

**Comment by josvanroosmalen** [comment]
should be fixed in 2.0
