### ISSUE TITLE
[BUG] LookupQuery returns error when it has empty documents

### ISSUE THREAD

**Issue by JhansiBonthu** [marklogic-community/pipes#331]
**Describe the bug**
In some cases,we need to use lookupQuery (which has multiple clauses)to retrieve the document and its been mapped to source data.If there is no documents matches to lookupQuery then it leads to error.

**To Reproduce**
1. Go to 'Graph'
2. Click on 'lookupQuery'
3. Write 3 clauses (collection query and 2 json property values quesries)
4. and then send the documents output to fn.head
5.send the fn.head output to source data(create any test source block)
6. when we run the pipe ,it leads to below error.

2020-10-19 11:23:35.947 Error: Exception occured during graph execution: XDMP-ARGTYPE: xdmp.type(Sequence()) -- arg1 is not of type xs.anyAtomicType

7. when we use sub=graph,there wont be any issues even it has sub documents.In my case,I'm pretty sure that we get only one document for lookupQuery so directly mapped the documents to source block in the main graph itself.

**Expected behavior**
It has to be handled,even though if we don't use sub graph.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by josvanroosmalen** [comment]
Jhansi please add a **minimal graph**, our mail this to me personally.

**Comment by josvanroosmalen** [comment]
Can fix in 2.0 if you deliver an minimal graph+input. See your customer mail.

**Comment by JhansiBonthu** [comment]
[Screenshots.zip](https://github.com/marklogic-community/pipes/files/5407686/Screenshots.zip)
As its sensitive data, i have n't attached the screenshot.Now,made a sample and adding screenshots for reference.I made 2 cases for reference.

**Comment by JhansiBonthu** [comment]
Sample ingestion script:
declareUpdate();
xdmp.documentInsert(
       '/example.json', {
					'OrderId': 166839, 
					'OwnerId': 3, 
					'ProductType': 'Virtual', 
					'Sku': 'CVSEO', 
					}  ,
       {collections : 'test'})




LookupQuery used in graph:
cts.andQuery(
[
cts.collectionQuery("test),
cts.jsonPropertyValueQuery("OrderId",12345),
cts.jsonPropertyValueQuery("productType","Virtual")
]
)

**Comment by JhansiBonthu** [comment]
Modify product type to some value to test negative case and it leads to error.

**Comment by josvanroosmalen** [comment]
Please supply the graphs in XML form

**Comment by josvanroosmalen** [comment]
Emailed the customer that they need to sent the graph.

**Comment by josvanroosmalen** [comment]
Issue should be fixed in release 2.0
