### ISSUE TITLE
[BUG] Auto Format Date is not working

### ISSUE THREAD

**Issue by JhansiBonthu** [marklogic-community/pipes#332]
**Describe the bug**
After upgrading the pipes to 1.4.Auto format date is not working.

**To Reproduce**
1. Go to 'Graph'
2. Click on 'Format' and select Auto Format Date
3. Click on Generate-> Current Date
4. Map Current Date to Auto Format Date as input.
5. It throws an error says as below.

2020-10-20 13:57:37.522 Error: Exception occured during graph execution: ReferenceError: r is not defined

**Expected behavior**
Auto format has to be worked as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/48585540/96583227-af6a0c80-12dc-11eb-8786-9d3040a633b5.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by josvanroosmalen** [comment]
This will be fixed in 2.0 Will add a unit test to the QA harness for this one.

**Comment by josvanroosmalen** [comment]
Unit test added. should be fixed in 2.0
