### ISSUE TITLE
[BUG]Pipes2.0 errors at runhubflow harmonize step:LookupbyValue is not a function

### ISSUE THREAD

**Issue by SabineVanEs** [marklogic-community/pipes#337]
**Describe the bug**
We implemented pipes version 2.0 and I was checking a few graphs to see if they were still working. After the check I saved the graphs to the project, reloaded modules and then wanted to run the runHubFlow Harmonize....
I got errors on several steps of the harmonization where in 3 out 6 graphs the error message is: "TypeError: r.executeLookupByValue is not a function or its return value is not iterable"

**To Reproduce**
1. Load the graph in Pipes
2. Click on Export DHF custom step module
3. Save project to project code
4. Check the 'Deploy to Mark Logic' box
5. Select the correct step
6. Click on Export
7. Click on Download a local copy of current graph
8. Copy the downloaded graph in the graphs folder of the local repository
9. In VSC run: ./gradlew mlReloadModules
10. In VSC run: ./gradlew hubRunFlow -PflowName=xxx
11. In VSC run: ./gradlew hubRunFlow -PflowName=Harmonizexxx

**Expected behavior**
At step 11 I expected all steps in the Harmonize flow to have run succesful. However, 3 out of 6 steps failed. This is the error message from 1 of the steps:

 "2" : {
      "flowName" : "HarmonizeSMS",
      "stepName" : "MapSMSToServiceobject",
      "stepDefinitionName" : "MapSMSToServiceobject",
      "stepDefinitionType" : "custom",
      "stepOutput" : [ "{\"stack\":\"TypeError: r.executeLookupByValue is not a function or its return value is not iterable\\n    at executeCustomStep (/custom-modules/custom/MapSMSToServiceobject/main.sjs:41:80)\\n    at main (/custom-modules/custom/MapSMSToServiceobject/main.sjs:32:17)\\n    at Flow.runMain (/data-hub/5/impl/flow.sjs:485:12)\\n    at Flow.runStep (/data-hub/5/impl/flow.sjs:343:58)\\n    at Flow.runFlow (/data-hub/5/impl/flow.sjs:211:12)\\n    at post (/marklogic.rest.resource/mlRunFlow/assets/resource.sjs:60:25)\\n    at callExtension (/MarkLogic/rest-api/lib/extensions-util.sjs:93:30)\\n    at applyOnce (/MarkLogic/rest-api/lib/extensions-util.sjs:111:10)\",\"message\":\"r.executeLookupByValue is not a function or its return value is not iterable\",\"name\":\"TypeError\",\"uri\":\"/data/SMS/smsinstallaties/negative1.json\"}", "{\"stack\":\"TypeError: r.executeLookupByValue is not a function 
or its return value is not iterable\\n    at executeCustomStep (/custom-modules/custom/MapSMSToServiceobject/main.sjs:52:94)\\n    at main (/custom-modules/custom/MapSMSToServiceobject/main.sjs:32:17)\\n    at Flow.runMain (/data-hub/5/impl/flow.sjs:485:12)\\n    at Flow.runStep (/data-hub/5/impl/flow.sjs:343:58)\\n    at Flow.runFlow (/data-hub/5/impl/flow.sjs:211:12)\\n    at post (/marklogic.rest.resource/mlRunFlow/assets/resource.sjs:60:25)\\n    at callExtension (/MarkLogic/rest-api/lib/extensions-util.sjs:93:30)\\n    at applyOnce (/MarkLogic/rest-api/lib/extensions-util.sjs:111:10)\",\"message\":\"r.executeLookupByValue is not a function or its return value is not iterable\",\"name\":\"TypeError\",\"uri\":\"/data/SMS/smsinstallaties/smsinstallaties2%20copy.json\"}", "{\"stack\":\"TypeError: r.executeLookupByValue is not a function or its return value is not iterable\\n    at executeCustomStep (/custom-modules/custom/MapSMSToServiceobject/main.sjs:52:94)\\n    at main (/custom-modules/custom/MapSMSToServiceobject/main.sjs:32:17)\\n    at Flow.runMain (/data-hub/5/impl/flow.sjs:485:12)\\n    at Flow.runStep (/data-hub/5/impl/flow.sjs:343:58)\\n    at Flow.runFlow (/data-hub/5/impl/flow.sjs:211:12)\\n    at post (/marklogic.rest.resource/mlRunFlow/assets/resource.sjs:60:25)\\n    at callExtension (/MarkLogic/rest-api/lib/extensions-util.sjs:93:30)\\n    at applyOnce (/MarkLogic/rest-api/lib/extensions-util.sjs:111:10)\",\"message\":\"r.executeLookupByValue is not a function or its return value is not iterable\",\"name\":\"TypeError\",\"uri\":\"/data/SMS/smsinstallaties/smsinstallaties2.json\"}" ],
      "fullOutput" : null,
      "status" : "completed with errors step 2",
      "totalEvents" : 4,
      "successfulEvents" : 1,
      "failedEvents" : 3,
      "successfulBatches" : 1,
      "failedBatches" : 0,
      "success" : false,
      "stepStartTime" : "2020-11-05T16:44:14.4866159+01:00",
      "stepEndTime" : "2020-11-05T16:44:14.6235552+01:00"
    },

**Screenshots**

**Desktop (please complete the following information):**
OS: Windows
Browser: Chrome
Version: Version 86.0.4240.75 (Official build) (64-bits)

**Additional context**
Other graphs using the LookupyValue block have the same issue. 
I prefer not to upload the graph or testdata here, but you can contact me if anything is needed.

**Comment by josvanroosmalen** [comment]
Hi Sabine,

Yes I found that out already a few days ago. It will be fixed in 2.0.1 This occurs when the lookup value does not find anything. 

I will issue a fix later today.

**Comment by SabineVanEs** [comment]
Hi Jos,

Thanks for the update, I will inform the projectteam.

Met vriendelijke groet,
With kind regards,


Sabine van Es - Bruins

[cid:image001.jpg@01D2FA51.2BE7C430]

Van: Jos van Roosmalen <notifications@github.com>
Verzonden: vrijdag 6 november 2020 09:26
Aan: marklogic-community/pipes <pipes@noreply.github.com>
CC: Es, Sabine van <svesbruins@feenstra.com>; Author <author@noreply.github.com>
Onderwerp: Re: [marklogic-community/pipes] [BUG]Pipes2.0 errors at runhubflow harmonize step:LookupbyValue is not a function (#337)


Hi Sabine,

Yes I found that out already a few days. It will be fixed in 2.0.1 This occurs when the lookup value does not find anything.

I will issue a fix later today.

**Comment by josvanroosmalen** [comment]
shipping 2.0.1
