### ISSUE TITLE
[BUG] stringtemplate returns as undefined when the input is empty

### ISSUE THREAD

**Issue by JhansiBonthu** [marklogic-community/pipes#341]
**Describe the bug**
stringtemplate returns as undefined when the input is empty

**To Reproduce**
1. Go to 'Generate'
2. Click on 'string template'
3. Don't provide any input and make it as empty'
4. See the output as "undefined"

**Expected behavior**
when there is no data then it returns the value as empty instead of undefined.

**Screenshots**
Attached sample graph and output.
[SampleGraphAndOutput.zip](https://github.com/marklogic-community/pipes/files/5509668/SampleGraphAndOutput.zip)

**Desktop (please complete the following information):**

**Additional context**

**Comment by josvanroosmalen** [comment]
I will look into this

**Comment by josvanroosmalen** [comment]
shipping bug.
