### ISSUE TITLE
[BUG]Map always returns empty after upgrading to 2.0.1

### ISSUE THREAD

**Issue by JhansiBonthu** [marklogic-community/pipes#342]
**Describe the bug**
Map always returns empty after upgrading to 2.0.1

**To Reproduce**
Attached sample json to reproduce the behavior. No need to ingest any data in database.
 
**Expected behavior**
Map has to produce the expected mapped values.

**Screenshots**
Attached zip file
[SampleToReproduce.zip](https://github.com/marklogic-community/pipes/files/5510519/SampleToReproduce.zip)

**Desktop (please complete the following information):**

**Additional context**

**Comment by josvanroosmalen** [comment]
Thanks this issue is reproducible

**Comment by josvanroosmalen** [comment]
2.0.2 shipping
