### ISSUE TITLE
[BUG] Not able to edit the Execute JavaScript block

### ISSUE THREAD

**Issue by SabineVanEs** [marklogic-community/pipes#343]
**Describe the bug**
When adding the Execute Javascript block to a graph it's not possible to type or to use the space bar. You have to write the code in a different application or in Query console and copy paste it into the block. 

**To Reproduce**
1. Go to a graph
2. Add the Execute Javascript block
3. Remove the default text and enter new text in it and try to use the space bar. 
4. No error, just not able to type or use space bar.

**Expected behavior**
Expected to be able to go through the text and edit it

**Screenshots**

**Desktop (please complete the following information):**
OS: Windows
Browser: Chrome
Version: Version 86.0.4240.75 (Official build) (64-bits)

**Additional context**

**Comment by josvanroosmalen** [comment]
Yes I have observed this as well a few weeks ago.

**Comment by josvanroosmalen** [comment]
shipping bug.
