### ISSUE TITLE
[BUG] Entity block properties are sorted Z to A

### ISSUE THREAD

**Issue by SabineVanEs** [marklogic-community/pipes#344]
**Describe the bug**
The Entity block properties are sorted Z to A instead of A to Z. 

**To Reproduce**
1. Go to pipes, start a new graph
2. Create an Entity block
3. Add Entity Block to graph
4. See screenshot

**Expected behavior**
Expected the properties of the entity block to be sorted from A to Z

**Screenshots**

![image](https://user-images.githubusercontent.com/72729991/98803379-f0a19800-2414-11eb-8f49-de89f22062f7.png)

**Desktop (please complete the following information):**
OS: Windows
Browser: Chrome
Version: Version 86.0.4240.75 (Official build) (64-bits)

**Additional context**

**Comment by josvanroosmalen** [comment]
I will look into this

**Comment by josvanroosmalen** [comment]
They are basically "unsorted". but will add sorting.

**Comment by josvanroosmalen** [comment]
shipping bug.
