### ISSUE TITLE
Document what blocks are, in the Wiki

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#35]
Explain what they do

- Source block
- Entity block

**Comment by josvanroosmalen** [comment]
Add some description, a screenshot, an example. Als minimum add a description

**Comment by sashamitrovich** [comment]
@josvanroosmalen, any particular blocks we should tackle 1st and in what order?
@epoilvet , could you take this one?

**Comment by sashamitrovich** [comment]
@josvanroosmalen, is this what you're looking for: https://github.com/marklogic-community/pipes/wiki/3.-What-is-a-Block-in-pipes-and-library-overview ?

**Comment by sashamitrovich** [comment]
We've added a lot of documentation to the Wiki. If new, specific requests come up, we will add new issues.
