### ISSUE TITLE
Support Gradle properties files

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#37]
It would be nice if Pipes could run in Gradle properties mode eg:

`java -jar *pipes.jar -gradleMode -environmentLabel=mydocker`

This should read properties from `gradle.properties` and override by `gradle-docker.properties`.

I can take care of the impl.

Tx

**Comment by sashamitrovich** [comment]
There are a few properties that are not part of gradle.properties so it would mean extending your gradle.properties with these.

Once you've done it, let me know so that we can document, please.

**Comment by sashamitrovich** [comment]
Should be supported out of the box, in fact:

https://docs.spring.io/spring-boot/docs/2.3.x/reference/html/spring-boot-features.html#boot-features-external-config-application-property-files

Probably a matter of specifying:

--spring.config.name
--spring.config.location

Try and let me know if it works.
