### ISSUE TITLE
Represent another graph as a block and allow to click from graph to graph

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#42]
Allow graph A to be represented as a block in graph B. When you click on that block in graph B you need to be able to "zoom in" graph A (the editor switches from showing B to A. Also you need to able to zoom out so return from A to B.

**Comment by sashamitrovich** [comment]
That is probably supported already bu Sub-Graph.
Check in https://github.com/marklogic-community/pipes/tree/master/Examples/Search and https://github.com/marklogic-community/pipes/tree/master/Examples/SubGraph

**Comment by sashamitrovich** [comment]
When I say check - you can upload these external graph files into the UI.

**Comment by sashamitrovich** [comment]
@josvanroosmalen , can you confirm that Subgraphs fulfil the functionality you need?

**Comment by sashamitrovich** [comment]
This is covered by the Subgraph functionality. We will use #68 to document better how Subgraphs work.
