### ISSUE TITLE
As a user I'd like to be able to run Pipes in a docker container

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#54]
@stuartMoorhouse, would you still like to tackle this?

**Comment by stuartMoorhouse** [comment]
Yes, looking at it now.

**Comment by paxtonhare** [comment]
I'm dockerizing pipes right now for Envision. Is the intent for this ticket that MarkLogic will also be dockerized? Is the idea to run 1 docker command and get a pipes+marklogic-dhf that just works?

**Comment by sashamitrovich** [comment]
@stuartMoorhouse  can comment more.
The intent is to create a docker container for Pipes as a separate one, create a container for MarkLogic from an available docker image on docker hub and configure the to work. The DHF project is available on the local FS (not in docker), in this scenario.

**Comment by sashamitrovich** [comment]
check 
https://github.com/marklogic-community/pipes/blob/master/docker/README.md

**Comment by sashamitrovich** [comment]
@stuartMoorhouse , could you create a wiki page (on GitHub wiki) that basically reflects the content of REAdme or, better yet, points to the README?

**Comment by stuartMoorhouse** [comment]
Hi, Yes I have added Pipes in a container to https://hub.docker.com/repository/docker/dhfpipes/pipes.

The intention as Sasha said is this container is run alongside a MarkLogic instance locally, in another container, etc. The README for the /docker directory describes how to set up MarkLogic in a container and Pipes in a container.

In the example, the DHF project is on the local machine but bind-mounted to both containers.

That feature does not include the orchestration necessary to run a MarkLogic container, install the DHF, then run Pipes and connect to MarkLogic.

**Comment by sashamitrovich** [comment]
Done.
