### ISSUE TITLE
As a user, I want to have to option to determine the type of graph output - JSON or XML

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#56]

**Comment by sashamitrovich** [comment]
@epoilvet, could we work on this, for an official 1.0 release this is probably important?

**Comment by taatuut** [comment]
@epoilvet this is a useful addition for existing XML/XQuery strongholds, also because it would enable them to see how the output looks when switching from XML to JSON (or vice versa) so it could ease (part of) the migration.
