### ISSUE TITLE
Complex BOM file was not parsed completely when creating from source

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#58]
The file was saved as json when ingested from DHF QS UI.

It only happens with JSON (when ingested as XML, it works properly).

**Comment by sashamitrovich** [comment]
[example_PS_BOM_2.xml.zip](https://github.com/marklogic-community/pipes/files/4158664/example_PS_BOM_2.xml.zip)

**Comment by epoilvet** [comment]
I miss the json version.

**Comment by sashamitrovich** [comment]
Run the ingestion step and output json.

**Comment by sashamitrovich** [comment]
@danielholgate, would be great if you could remember what the issue is and document here. Thanks.

**Comment by epoilvet** [comment]
Fixed on Master
