### ISSUE TITLE
Only user with username “admin” is able to deploy the backend

### ISSUE THREAD

**Issue by bvcnl** [marklogic-community/pipes#59]
As admin on MarkLogic I have another username then “admin”, say “myspecificusername”. When configuring the correct credentials in the properties file with mlUsername=myspecificusername, the deploy fails. When I change my username in MarkLogic to “admin” and reflect that in the properties file, the deploy is successful.

**Comment by sashamitrovich** [comment]
@josvanroosmalen, have you tried deploying with "flowDeveloper" or someone else?

**Comment by sashamitrovich** [comment]
@bvcnl,

To debug this, I need some additional info:

- what's the name of your staging DB?
- are you using different mlManagePort, mlAdminPort or mlAppServicesPort?
- which port(s) are you using in your DHF project?

Thanks!

**Comment by sashamitrovich** [comment]
OK, issue found! The fix will be in the next release (beta-2).

**Comment by sashamitrovich** [comment]
Done.

**Comment by bvcnl** [comment]
Thank you!

Op do 6 feb. 2020 om 12:27 schreef Saša Mitrović <notifications@github.com>
