### ISSUE TITLE
Allow mlDhfRoot to work with relative paths

### ISSUE THREAD

**Issue by derms** [marklogic-community/pipes#61]
E.g.

`mlDhfRoot=../`

**Comment by sashamitrovich** [comment]
Thanks for reporting. Out of curiosity, why  is this needed (trying to understand the use case)?

**Comment by derms** [comment]
I wanted to have my pipes config in a subdirectory of my dhf project. this way when another user checks out the project, they don't need to configure the mlDhfRoot to an absolute directory on their filesystem.

**Comment by sashamitrovich** [comment]
Excellent, thanks for clarifying!

**Comment by sashamitrovich** [comment]
@derms, want to tackle this? The amount of work should be minimal.

**Comment by derms** [comment]
@sashamitrovich sure ok i'll do it.

**Comment by sashamitrovich** [comment]
Just tried this, relative paths do work. Nothing to be done here.
