### ISSUE TITLE
Serious issue: Pipes deliver unreliable results

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#64]
Here is a serious Pipes issue. **We are losing information**

Below is a minimal reproduction, what this shows is:

-	2 staging document with id = 1 and id = 2
-	With a Pipes graph we map Id -> Code. We expect 2 final documents with Code = 1 and Code = 2. 
-	However, we end up with 2 docs with code = 2 with one having attachment = ID = 1 (see screenshot)
-	SO I am missing info and that is Code = 1.

![image](https://user-images.githubusercontent.com/9380618/73945108-11701680-48f4-11ea-9826-c25ba4cb6364.png)

Reproduction

Run this against staging:

```
xquery version "1.0-ml";
(xdmp:document-insert("test.xml",<root><ID>1</ID></root>,map:map()=>map:with("collections","TEST")),
xdmp:document-insert("test2.xml",<root><ID>2</ID></root>,map:map()=>map:with("collections","TEST")))
```

**DHF:**

-	Create an Entity "Test" with 1 property “Code” type String
-	Create a custom flow based on TEST which we will later overwrite. This custom flow should run on collection TEST. 
-	Run `mlDeploy`

**Pipes:**

-	Create Source block based on collection TEST and add ID. 
-	Create Entity block Test
-	Link input to attachment and to input of the Sourceblock. Link ID to Code and Node to Instance. 
-	(or Load the attached graph)

![image](https://user-images.githubusercontent.com/9380618/73945273-5d22c000-48f4-11ea-8a43-03f353961ab6.png)

-	Overwrite the custom flow (or use the one attached)
-	Run custom flow. 
-	If you do not get this immediately, rerun the custom flow again (I get it consistent wrong).

**Comment by josvanroosmalen** [comment]
@danielholgate reported that he could reproduce this bug.

**Comment by epoilvet** [comment]
Fix ready to be tested in current Master branch

**Comment by sashamitrovich** [comment]
Fix confirmed on master. Thanks, @epoilvet!
