### ISSUE TITLE
As a user I’d like to be able to log in using the interface

### ISSUE THREAD

**Issue by AsanaJ** [marklogic-community/pipes#65]
Currently the username/password have to be entered in the properties file or on the command line. It would be great if I can log in using the Pipes UI (similarly to logging into the Data Hub Quickstart UI).

**Comment by sashamitrovich** [comment]
Thanks for reporting, accepted. It's a duplicate of #53, we'll be tracking it there. I'm going to close this one as duplicate if you don't mind?

**Comment by AsanaJ** [comment]
Hi Saša.

Ah okay - sorry about that and thank you.

Cheers,
Johan

fre. d. 7. feb. 2020 08.48 skrev Saša Mitrović <notifications@github.com>:

**Comment by sashamitrovich** [comment]
Yeah, no worries, thanks for reporting, pls. keep reporting and we'll sort it out whether similar/same issue exists or not.

**Comment by sashamitrovich** [comment]
Will ship in beta.3.

**Comment by AsanaJ** [comment]
Awesome - thanks!

Den tir. 3. mar. 2020 kl. 15.27 skrev Saša Mitrović <
notifications@github.com>:
