### ISSUE TITLE
More Clear UI that subgraphs works on arrays

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#68]
Currently a first input of a subgraph is an array. So the output of a subgraph is also an array. 

It need to be clearer that that is the case, also it should be clear what a second input or output is. Is a second input/output also an array or can that e.g. be a constant which is feed in / out?

**Comment by epoilvet** [comment]
Now the label of the first slot is automatically updated with [Array]. Note: 
Doc to be updated.

**Comment by sashamitrovich** [comment]
Done!
