### ISSUE TITLE
Preview based on URI does not work

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#72]
Preview based on URI does not work. I tried to run the "subgraph" example with the sample XML which I saved to "/subgraph.xml". When I then enter "/subgraph.xml" in the optional URI, you get an error on xdmp:documentGetCollection(null). 

Also you still need to select a collection if you want to run this. This does not make sense if I specify 

So there are 2 options: 

- DB + Collection  => use random 
- DB + Optional URI without collection => use specific uri from that DB. 

So the random doc switch can be removed. There should be 2 radio buttons: sample DB (DB+Collection) or second radio button: specify URI + DB.

**Comment by josvanroosmalen** [comment]
Sorry the problem is a bit different. I had inserted the doc in FINAL, but when I select STAGING I get this annoying error, that is because it can not find the URI.

**Comment by josvanroosmalen** [comment]
You still need to mention the collection which does not make sense if I applied a URI.

**Comment by sashamitrovich** [comment]
Yes, you do have to. It makes sense in the following scenario:
- I specify a collection for my source block
- Pipes will take 10 random docs and create the document tree
- I notice that some elements I expected are missing
- So I **supplement** the list by adding a specific URI from that collection

The question is: how much freedom do we want to give to Pipes users to screw things up? You're a power user so for you this doesn't make sense. For many others it will make sense.

Do you have a suggestion how to do this better, @josvanroosmalen ?

**Comment by sashamitrovich** [comment]
When URI field is used, enable the "Execute Preview", disable "Collection" and disable "Random Doc".

**Comment by sashamitrovich** [comment]
Merged to master.
