### ISSUE TITLE
Implement onCodeGeneration for all other Core blocks

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#73]
I delivered a native JS compiler framework which relies on an `onCodeGeneration` function. For not all core blocks they are implemented. 

The task is to implement this for other blocks as well. See the `onCodeGeneration` for the ones it is already implemented as guideline how it works.

**Comment by sashamitrovich** [comment]
Is this for @epoilvet  or @josvanroosmalen , who will work on it?

**Comment by josvanroosmalen** [comment]
Will close. We wil use a different approach for this.
