### ISSUE TITLE
Preview will crash on empty output

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#77]
If you do in a custom block (or a core block result in this) a `setOutputData(0,[])` then feed that in a source block, entity block etc, then the Preview/runtime will crash.  It will crash in `GraphOutputDHF.prototype.onExecute` on `if(output.constructor === Array)`  because `output` will be `undefined`.

**Comment by sashamitrovich** [comment]
@josvanroosmalen , can you supply a sample graph and data for this? Thanks.

**Comment by epoilvet** [comment]
I pushed an update to avoid crash in GraphOutputDHF but still need to test on actual graph which had an issue. So yes, sample graph would help.

**Comment by josvanroosmalen** [comment]
@sashamitrovich see my mail of 13:53 of March 2nd 2020.

**Comment by sashamitrovich** [comment]
Tested now, cannot reproduce. Has been fixed.
