### ISSUE TITLE
Xpath block throwing error

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#89]
@josvanroosmalen , here's a sample graph and a source document to use to debug this problem:
[xpath-bug.zip](https://github.com/marklogic-community/pipes/files/4297050/xpath-bug.zip)

**Comment by josvanroosmalen** [comment]
I am checking this now

**Comment by josvanroosmalen** [comment]
Please retest.

**Comment by sashamitrovich** [comment]
Confirmed fix.
