### ISSUE TITLE
As a user I want to tear-down the Pipes application when I have finished using it.

### ISSUE THREAD

**Issue by sashamitrovich** [marklogic-community/pipes#9]
Enable a user to remove the Pipes code from their DHF.

Use cases:

- A user tries Pipes and doesn't want to keep using it
- A user wants to do a fresh install of Pipes
- A user wants to remove Pipes as part of troubleshooting their DHF code

**Comment by danielholgate** [comment]
There are also components that get saved to the staging DB during Pipes usage (Graphs, Blocks etc). Each are currently are in a single collection which matches their function (/type/savedGraph,  /type/savedBlock etc) but would be handy to add a second collection to everything called "marklogic-pipes" etc so we can do a collection.delete and remove all artifacts

**Comment by sashamitrovich** [comment]
Done. 
It's now part of the 0.8-beta.2 pre-release
