### ISSUE TITLE
String/uuid is not compiling to native SJS

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#92]
As reported by @sashamitrovich , the IOT graph is not compiling to native code. This is because the string/uuid string is not compiling to native code.

**Comment by josvanroosmalen** [comment]
It is getting removed because string/uuidstring is considered a dead node.

**Comment by josvanroosmalen** [comment]
The IOT graph should now compile correctly. Please retest.

**Comment by sashamitrovich** [comment]
Fix confirmed, thanks @josvanroosmalen.
